version: '3'
services:
  composer-cli:
    image: composer:latest
    user: '1000:1000'
    volumes:
      - ./:/var/src
    working_dir: /var/src

  php-fpm:
    image: bitnami/php-fpm:8.1
    volumes:
      - ./:/var/src

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/src
    ports:
      - "8081:80"
    depends_on:
      - php-fpm